// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedaqc--PqkZOvFYcyW0AZIinLSsZfxHk',
    appId: '1:373425238182:web:fcf91efd5eee56a4810467',
    messagingSenderId: '373425238182',
    projectId: 'the-one-step',
    authDomain: 'the-one-step.firebaseapp.com',
    storageBucket: 'the-one-step.appspot.com',
    measurementId: 'G-6BMWN67DFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAam6sPDzCYh0OVecty9e21HhV0eDA_Aqs',
    appId: '1:373425238182:android:82ac9306224cd7ee810467',
    messagingSenderId: '373425238182',
    projectId: 'the-one-step',
    storageBucket: 'the-one-step.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpq542ZG3Zjrt9GUiDB46f-95Zc9ZrPog',
    appId: '1:373425238182:ios:f17322dffcf87c7f810467',
    messagingSenderId: '373425238182',
    projectId: 'the-one-step',
    storageBucket: 'the-one-step.appspot.com',
    iosBundleId: 'com.example.theHanStep',
  );
}
